defaults:
  - user: gwb301
  - model: PlanT

exp_folder_name: PlanT2_train
hydra:
  run:
    dir: outputs/${exp_folder_name}/${expname}/${hydra.job.override_dirname}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    config:
      override_dirname:
        exclude_keys:
          - expname
        kv_sep: '='
        item_sep: '_'

lrDecay_epoch: 29

# seed: 1234
debug: False
visualize: False
overfit: 0
resume: True
resume_path: ""
use_caching: True
custom_sampler: False
gpus: 2
# trainset_size: 1
# benchmark: longest6

expname: DEBUG
wandb_name: training_PlanT_${hydra:job.override_dirname}
save_dir: ${hydra:run.dir}

# data_dir: /mnt/lustre/work/geiger/bjaeger25/garage_2_cleanup/results/data/garage_v1_2024_11_07/data # Path to the data directory of the first part of the dataset (ending '_1')
# data_dir: /home/geiger/krenz73/coding/07_simlingo/simlingo_cleanup/database/simlingo_v2_2025_01_10/data # Path to the data directory of the first part of the dataset (ending '_1')
# data_dir: /home/geiger/krenz73/coding/07_simlingo/carla_garage/database/plant2_v1_2025_01_12/data
data_dir: /home/simon/PlanT_2_cleanup/PlanT_2_2025_07_24/data

